#!/usr/bin/env bash
# bash script that installs HAProxy & makes configurations to meet the following requirements:

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5432-web
    bind *:80
    mode http
    balance roundrobin
    server 6121-web-01 54.198.83.191:80 check
    server 6121-web-02 54.175.164.90:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
