#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to respect
# above requirements (this script will be run on the server itself)
# bash script to install nginx web server
#   - Nginx should be listening on port 80
#   - Return page containing "Holberton School" when queried

sudo apt update 
sudo apt install nginx -y
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html 
sudo service nginx restart
