#!/usr/bin/env bash
# bash script that configures a Nginx server to redirect '/redirect_me' to 'http://youtube.com/'
# redirection is configured as a "301 Moved Permanently"

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "This is Oreste from Holberton School :)" | sudo tee /var/www/html/index.html > /dev/null

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.github.com\/tuyishimejeandamour;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
